#ifndef MAC_H_
#define MAC_H_
typedef enum {
	PKT_NOP = 0,
	PKT_ACK = 1,
	PKT_APP_DATA = 2,
	PKT_VERSION_REQUEST = 8,
	PKT_VERSION_RESPONSE = 9,
	PKT_MCU_ID_REQUEST = 10,
	PKT_MCU_ID_RESPONSE = 11,

	// OTA functions only available in bootloader mode
	PKT_OTA_ENTER_BOOTLOADER = 0x10,
	PKT_OTA_FLASH_WRITE = 0x11,
	PKT_OTA_FLASH_CRC_REQUEST = 0x12,
	PKT_OTA_FLASH_CRC_RESPONSE = 0x13,
	PKT_OTA_REBOOT = 0x14,
	PKT_OTA_EXIT_BOOTLOADER = 0x15,
	PKT_OTA_FLASH_REQUEST = 0x16,
	PKT_OTA_FLASH_RESPONSE = 0x17,
	PKT_OTA_REPROG_TEST = 0x18,

	PKT_ISP_ENTER_BOOTLOADER = 0x1e,


	PKT_RELAY = 0x42,
	PKT_REMOTE_CMD = 0x44,
	PKT_EXEC_MEM = 0x45,
	PKT_START_PINGPONG = 0x50,
	PKT_LOCATION_REPORT = 0x52,
	PKT_STATUS_REPORT = 0x53,
	PKT_STATUS_RESPONSE = 0x73,
	PKT_LED_BLINK = 0x55,
	PKT_RADIO_REG_READ = 0x58,
	PKT_RADIO_REG_WRITE = 0x59,
	PKT_MEM_READ_REQUEST = 0x3c,
	PKT_MEM_READ_RESPONSE = 0x1c,
	PKT_MEM_WRITE = 0x3e,
} packet_type;
#endif
