#ifndef __RFM98_H
#define __RFM98_H

// Autogenerated RFM98 headers generated with ICRDL tool
#include "rfm98_rdl.h"

void rfm98_init(void);
void rfm98_config(void);

int rfm98_lora_mode(uint8_t mode);

int rfm98_is_packet_ready();
int rfm98_frame_rx(uint8_t *buf, int maxlen);
void rfm98_frame_tx(uint8_t *buf, int len);

int rfm98_last_packet_rssi();
int rfm98_last_packet_snr();
int rfm98_last_packet_crc_ok();

// Check for received packet on RFMxx
// TODO: need HAL layer
#define IS_PACKET_READY(x) rfm98_is_packet_ready()

#endif /* end __RFM98_H */
