#ifndef __RFM98_H
#define __RFM98_H

// Autogenerated RFM98 headers generated with ICRDL tool
#include "rfm98_rdl.h"

void rfm98_init(void);
void rfm98_config(void);

int rfm98_mode(uint8_t mode);

int rfm98_frame_rx(uint8_t *buf, int maxlen);
void rfm98_frame_tx(uint8_t *buf, int len);

uint8_t rfm69_payload_ready();
uint8_t rfm69_is_pll_lock();

#endif /* end __RFM98_H */
